micronaut:
  application:
    name: kafkactl
  http:
    client:
      read-timeout: 30s
      ssl:
        insecure-trust-all-certificates: true

logger:
  levels:
    ROOT: OFF
    io.micronaut.http.client.netty.DefaultHttpClient: OFF # See HTTP requests and responses
    io.micronaut.http.client.netty.ssl.NettyClientSslBuilder: OFF # Disable warns about trust all certificates

kafkactl:
  version: @version@
  table-format:
    AccessControlEntry:
      - "ACL:/metadata/name"
      - "GRANTED_BY:/metadata/namespace"
      - "GRANTED_TO:/spec/grantedTo"
      - "TYPE:/spec/resourceType"
      - "RESOURCE:/spec/resource"
      - "PATTERN:/spec/resourcePatternType"
      - "PERMISSION:/spec/permission"
      - "AGE:/metadata/creationTimestamp%AGO"
    AuthInfo:
      - "NAMESPACE:/spec/namespace"
      - "VERBS:/spec/verbs"
      - "RESOURCES:/spec/resources"
    ChangeConnectorState:
      - "CONNECTOR:/metadata/name"
      - "STATUS:/status/code"
      - "ERROR_MSG:/status/errorMessage"
    ConnectCluster:
      - "CONNECT CLUSTER:/metadata/name"
      - "URL:/spec/url"
      - "STATUS:/spec/status"
      - "ERROR_MSG:/spec/statusMessage"
    Connector:
      - "CONNECTOR:/metadata/name"
      - "WORKERS:/spec/connectCluster"
      - "CLASS:/spec/config/connector.class"
      - "TOPICS:/spec/config/topics"
      - "AGE:/metadata/creationTimestamp%AGO"
    ConsumerGroupResetOffsetsResponse:
      - "CONSUMER_GROUP:/spec/consumerGroup"
      - "TOPIC:/spec/topic"
      - "PARTITION:/spec/partition"
      - "OFFSET:/spec/offset"
    Context:
      - "NAME:/metadata/name"
      - "NAMESPACE:/spec/namespace"
      - "API:/spec/api"
      - "TOKEN:/spec/token"
    DeleteRecordsResponse:
      - "TOPIC:/spec/topic"
      - "PARTITION:/spec/partition"
      - "OFFSET:/spec/offset"
    KafkaUserResetPassword:
      - "NAMESPACE:/metadata/namespace"
      - "CLUSTER:/metadata/cluster"
      - "USER:/metadata/name"
      - "PASSWORD:/spec/newPassword"
    Namespace:
      - "NAMESPACE:/metadata/name"
      - "CLUSTER:/metadata/cluster"
      - "USER:/spec/kafkaUser"
      - "CONNECTS:/spec/connectClusters"
      - "LDAP:/metadata/labels/support-group"
      - "CONTACTS:/metadata/labels/contacts"
    ResourceDefinition:
      - "KIND:/metadata/name"
      - "NAMES:/spec/names"
      - "NAMESPACED:/spec/namespaced"
      - "SYNCHRONIZABLE:/spec/synchronizable"
    ResourceQuotaResponse:
      - "QUOTA:/metadata/name"
      - "COUNT/TOPICS:/spec/countTopic"
      - "COUNT/PARTITIONS:/spec/countPartition"
      - "DISK/TOPICS:/spec/diskTopic"
      - "COUNT/CONNECTORS:/spec/countConnector"
      - "USER/CONSUMER_BYTE_RATE:/spec/consumerByteRate"
      - "USER/PRODUCER_BYTE_RATE:/spec/producerByteRate"
    RoleBinding:
      - "ROLE_BINDING:/metadata/name"
      - "GROUP:/spec/subject/subjectName"
      - "VERBS:/spec/role/verbs"
      - "RESOURCES:/spec/role/resourceTypes"
    Schema:
      - "SUBJECT:/metadata/name"
      - "ID:/spec/id"
      - "VERSION:/spec/version"
      - "CONFIG:/spec/compatibility"
      - "TYPE:/spec/schemaType"
    SchemaCompatibilityState:
      - "SUBJECT:/metadata/name"
      - "CONFIG:/spec/compatibility"
    SchemaList:
      - "SUBJECT:/metadata/name"
    Topic:
      - "TOPIC:/metadata/name"
      - "RETENTION:/spec/configs/retention.ms%PERIOD"
      - "POLICY:/spec/configs/cleanup.policy"
      - "AGE:/metadata/creationTimestamp%AGO"
    VaultResponse:
      - "CLEAR_TEXT:/spec/clearText"
      - "ENCRYPTED_TEXT:/spec/encrypted"
  retry:
    apply:
      delay: "2s"
      attempt: "10"
      multiplier: "1.0"
    delete:
      delay: "2s"
      attempt: "10"
      multiplier: "1.0"
  contexts:
    - #  current-namespace: namespace
      #  api: http://localhost:8080
      #  user-token: token
      #  contexts:
      #    - context:
      #        user-token: token
      #        namespace: namespace
      #        api: http://localhost:8080
      #      name: local
      #    - context:
      #        user-token: token
      #        namespace: namespace
      #        api: https://dev-ns4kafka.com
    #      name: dev
